# Generated by Django 5.2.15 on 2026-06-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('analgesic', 'Analgesic / Pain Relief'), ('antibiotic', 'Antibiotic'), ('antimalarial', 'Antimalarial'), ('antiviral', 'Antiviral'), ('vitamin', 'Vitamin / Supplement'), ('other', 'Other')], default='other', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
