# Generated by Django 5.2.15 on 2026-09-15 00:30

from django.db import migrations, models
import uuid

def set_existing_users_verified(apps, schema_editor):
    """Set all existing users as verified and give each a unique token."""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for user in CustomUser.objects.all():
        user.email_verified = True
        user.verification_token = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        # Step 1: Add fields WITHOUT unique constraint
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4),  # no unique=True yet
        ),

        # Step 2: Set unique values for all existing rows
        migrations.RunPython(
            set_existing_users_verified,
            reverse_code=migrations.RunPython.noop
        ),

        # Step 3: NOW add the unique constraint
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]